services: 
    db:
      container_name: postgres
      image: postgres:15.2
      restart: always
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - 5433:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - twitch_pet-backend

    redis:
      container_name: redis
      image: redis:5.0
      restart: always
      ports:
        - 6379:6379
      command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0
      environment:
          - REDIS_PASSWORD=${REDIS_PASSWORD}
      volumes:
        - redis_data:/data
      networks:
         - twitch_pet-backend

volumes:
    postgres_data:
    redis_data:
networks: 
  twitch_pet-backend: